### ISSUE TITLE
Script to inject SVG icons into HTML

### ISSUE THREAD

**Issue by atisawd** [atisawd/boxicons#6]
if someone could help with the script to inject the SVG icons into HTML using JS , would really appreciate it.

**Comment by purtuga** [comment]
Hi @atisawd - First: thanks for sharing this library of icons. I love the fact that it uses SVG, which makes it very portable and self-contained.
I was just coming here to post a new issue and let you know that I will likely use this library to convert every svg image into a web component custom element and if you would be interested in hosting those as part of this library... It would not necessarily be a script to inject them, as this issue is requesting, but IMO - better :) 

Let me know if you would have interest in such a contribution. If not, that's cool too.

**Comment by atisawd** [comment]
This sounds exactly what i need. Are there any examples you could provide? or is this the same method used by fontawesome and ionicons ? if yes the please do go ahead :+1:

**Comment by purtuga** [comment]
Happy to hear. 
I have not worked with those recently, but my guess is more like ioniccons since it is built as a web components.  I will detail here first what I'm thinking for an api before I get started. In the mean time, here is a quick prototype of one of your icons:

https://codepen.io/purtuga/pen/QxVLvN?editors=1010

This quick example will work only in Chrome, since its not fully integrated with the polyfills that make web components work in browsers that don't yet support it. I will likely use my base class for CE ([here](https://github.com/purtuga/ComponentElement)) since it already supports the polyfills.

The CE in this example supports two attributes: `size` and `color`:

```html
<box-icon-filter size="128px 128px" color="blue"></box-icon-filter>
```

I'll post back soon.

**Comment by atisawd** [comment]
This looks  good, this does inject svg in place of the element box-icon-filter . I am assuming it will have a 'name' attribute to chose the icon from the list .  Ionicons  use the web components in their though case the svg is not inside a shadow DOM and you can change the color and size with 'color' and 'font-size' property in CSS, and the user can tweak the SVG with CSS. is this possible?

**Comment by purtuga** [comment]
The beauty of custom elements is that there is no need for replacement of temporary dom elements.  The icon is a dom element just like any other dom element.  So a user, instead of writing something like `<i class="boxicon boxicon-filter"></I>` they would just use the custom HTML tag for the icon: `<box-icon-filter></box-icon-filter>

I noticed that ionic allows for the URL to the icon to be defined.  That implies that a CDN must be used to host all of the SVGs or a consumer of your icons would have to host them somewhere.  I guess it's a matter of preference and design.

Do you rather expose one single HTML element (say `<box-icon>` and have that support a `src` attribute that points at the svg that should be used?
Or,
Build each icon into a single self-contained element that require no additional web calls?

I prefer self contained, but really, both can be done.  I think one goal is to make it part of the build so that it just generates them.


Paul

-- sent from mobile

**Comment by atisawd** [comment]
Sorry for the late replay man , i was busy with the new release, anyways ionicons store only the 'paths' of the  svg files and create an svg component when called upon

**Comment by purtuga** [comment]
Ok. I will see if can start working on this over the weekend. How is this for API:

HTML default tagName: `box-icon`
Supported HTML element attributes:

```html
<box-icon
    name="adjust|alarms|etc...."
    size="xs|sm|md|lg"
    rotate="90|180|270"
    flip="horizontal|vertical"
    border="square|circle"
    animation="spin|tada|flashing|burst|fade-left|fade-right|spin-hover|tada-hover|flashing-hover|burst-hover|fade-left-hover|fade-right-hover"
></box-icon
```

I will include a Class static property on the Custom Element to store the CDN url that points to the images (SVG) folder, so that users (if they want to) can change it. I also plan to expose the function that will actually load the svg images on the Class as well (static method) so that advanced users can also gain control over that (ex. for my own usage, I will be packaging up only certain icon SVG files with my applications)

Example usage will be something like this:

- include the custom element script:

```html
<script src="url/to/cdn/box-icon-element.js></script>
```
- Add an icon on the page by using the `<box-icon>` html element:

```html
<box-icon name="filter"></box-icon>
```

Please let me know if there is anything special about your dev setup. I will be changing the build (webpack) configuration to output a distribution file called `box-icon-element.js`. 

/Paul

**Comment by atisawd** [comment]
I am planning on adding solid versions of the icons too in the near future, they are ready already , but will release it a week or two later. But the solid versions are only for a few icons. So an attribute for the style would be great , where there is a check to see if the solid version exists if no then , just the normal version.

**Comment by purtuga** [comment]
Actually: now that you mention you create the bundle separately...

I just looked at what you include in the npm package you publish and looks like you are not including the svg images there... (I looked at this: https://unpkg.com/boxicons@1.0.7/ )
Will need to add those so that they can be loaded dynamically.    

I also noticed that the version you have in the `package.json` does not match the version you publish with... Any chance you can sync those up?  reason: that would be used during a build to automatically adjust the CDN url so that it points at the expected version of the library.

**Comment by atisawd** [comment]
hmm thanks for that i will update the package.json file immediately

**Comment by purtuga** [comment]
Yes, we can include the svg icons right into the bundle (as inline text), but that will mean that your bundle will be large since it will include all icons regardless if the user will use them or not. 

Not sure there is a right way or wrong way... In order to preserve bandwidth and make an app load faster, we usually don't include what we don't use in a bundle (if possible). When you referenced ionicicon above, I looked briefly at how they are doing it and they don't bundle them - but rather load them as needed from the CDN.  

But: we could build both version:s one that is small in size, but loads icons from a CDN on demand... and another that includes them all (self-contained). 

BTW: regardless - you might still want to consider adding the icons to the npm package - so that your project can be consumed as a library by app authors who might actually just want to use the SVGs and not the styles.

**Comment by atisawd** [comment]
Those are great points man, i published a new version with svg in npm 1.1.1, you can check it here  https://unpkg.com/boxicons@1.1.1

**Comment by purtuga** [comment]
I was able to spend some time on this yesterday and its pretty close to complete. Just need to work on some additional webpack build changes. 

A few questions:

1. Where do you want the bundle (build output) to be save to?  The file that will be output should be included in your npm package (I'm not sure how you are creating that)
2. Regarding documentation - how do you want to handle that?  Did you want me to write a README file for it or will handle it in some other way?
2. Right now I just created a dummy HTML test file to use during development - did you want me to also commit that?

### Re: published packages
Another item to note is that currently, the building of the custom element will use the version number in the `package.json` to automatically set the CDN url to include that. You seem to be creating NPM packages with some other configuration, so you likely need to sync those up. 

Also, one other suggestion is to also include the `src/` folder in the published packages - there may be users that prefer to use the Custom Element under a different html tagName, thus having direct access to the Class would be optimal.

-----

You can review the code changes done thus far here: https://github.com/atisawd/boxicons/compare/master...purtuga:master

**Comment by atisawd** [comment]
Sorry for the late reply , Wow this is good news

1. You can add the files in a build folder inside the static folder and i will add it to the npm package, if you have a better way do tell me 
2.  You can go ahead and edit the readme document since you have the best idea regarding the code, i will copy it for the doc on the website
3. Yup do that

Will sync the version numbers every time :+1: 

What should be included in the src/ folder?

**Comment by atisawd** [comment]
Should i create a pull request?

**Comment by purtuga** [comment]
Thanks for the responses.
I will make some final changes and send you a pull request a little later.

Paul

-- sent from mobile

**Comment by atisawd** [comment]
Cool thanks, excited to the see the result

**Comment by purtuga** [comment]
Ok.. sent Pull request (see #7 ).
All pretty much done... needs testing in different browsers.
Note that I opted to output the build bundle to `dist/` - that is a more standard path in git repos.

**Comment by atisawd** [comment]
This looks perfect honestly, one question , can i change the name of the js file from box-icon-element.js to boxicons.js?
will publish it in the npm package tomorrow

**Comment by atisawd** [comment]
It wont work on the IE browsers .  

Is it not possible to inject the styles with the JS file and instead of shadow DOM containing the svg element, just inject the svg outside .

**Comment by purtuga** [comment]
Re: renaming file
Sure. You can rename it.  Let me know if you would like me todo it. You will need to change it in the webpack configuration and the dev HTML file.

Re: not working in IE
It was working for me when I tested it yesterday. I'll see if I have some time later to test it again.


Paul

-- sent from mobile

**Comment by purtuga** [comment]
I'm not seeing a problem in IE... can you send me a link to an sample that is failing for you so I can take a look at what it looks like?

Here is one I creating that is loading the new `box-icon-element.js` from github:
https://codepen.io/purtuga/pen/QxVLvN?editors=1000

Loaded this in Chrome, Firefox, IE and iOS and all looks good.

**Comment by purtuga** [comment]
Glad to hear its working.  I'm probably not going to be able to do anything for the next few days on this... I'll try to see what the solids look like once you upload them.

**Comment by atisawd** [comment]
cool you can do it next weekend maybe , so till then i can get the solid versions online

**Comment by atisawd** [comment]
Hi , i worked on your code , so that it is compatible with the new version , and have published in the latest version , please do check

**Comment by luciorubeens** [comment]
Hey guys :wave: @atisawd thanks for this library! And @purtuga great patch.

However I saw that is attaching `animate.css` and `transformations.css` for each element. Do you think could we inject this stylesheets to the head instead? Or just import when it's set as an attribute.

**Comment by purtuga** [comment]
Hi @atisawd .
I'm not at a computer this weekend, so can't fully review.  But from my phone, the only thing that stands out is the change you made to `cdnUrl`. You changed it to use `latest` tag, which is ok if you *never* introduce a backwards incompatible change. The `latest` tag is updated with every release you upload to npm, so with every release you are potentially impacting all of the users of this custom element across all versions (if they did not change 'cdnUrl' property in their usage). Because the custom element is only using the CDN URL to load images, the impact should be minimal - but something that you should consider.

Paul

-- sent from mobile

**Comment by atisawd** [comment]
Hmm the plan is to add icons to the same folders, so there won't be any changes, but I will change the code immediately from latest, it was stupid of me to do so

**Comment by atisawd** [comment]
And I agree with @luciorubeens wouldn't it be better if the CSS is injected in the head?

**Comment by purtuga** [comment]
Hi @luciorubeens
That is common of Custom Elements that use shadowDom. ShadowDom encapsulates the styles so that they never interfere with any other styles outside of the element. Placing the elements in the global space would negate that feature.  Example: what if the page already has an animation named 'tada' that does something completely different?

As it stands, boxicons has two usage approaches: a CSS style sheet approach, where you do load the stylesheet globally and use its CSS styles,
And,
A custom element usage where you load the custom element code once and then use the custom HTML tag to define your icon element.

So for those users that are not confortable with custom elements, the CSS stylesheet approach will likely be the preferred route.

--

All that being said - yes, you could change the custom element to support global styles instead, but several things would be impacted - a few I can think of now is:

- no use of shadowDom (global styles do not penetrate shadowDom)
- the custom element template would have to change to take into consideration that fact that it would now be public and accessible/styled from the global document
- styles would have to be changed (don't think we can use ':host' pseudo selector)
- would not be able to support a different custom element tagName. That's because the styles would likely be tied to a tagName.


Just curious: why do you believe it would be better to have it outside?

(Btw: I understand it looks strange if you never built a custom element using the native web platform)

Paul

**Comment by atisawd** [comment]
What If we add a prefix to the CSS and add a prefix  through the js

**Comment by purtuga** [comment]
@atisawd ,
Sure. There are solutions that can be implemented to try to avoid some of the issues that native Web Components provide a solution for. But if you do that, then what is the benefit of having a Custom Element? Essentially, you are just re-creating a global CSS library - which you already have (the one that uses font icons).

I personally am not seeing a good reason for redesign the Custom Element to remove the encapsulation. My vote would be to leave it as is.

BTW: I will not take personally if you still decided to change it to meet your needs :-)

Paul

-- sent from mobile

**Comment by atisawd** [comment]
i read up on the web components , and agree , that there is no good reason to do it , its good that the styles are separated, and it looks like some of the css can be changed by the user too, thanks for this @purtuga :+1:

**Comment by atisawd** [comment]
@purtuga sorry to bother you but i tested in different browsers but it isnt working on firefox on ie , the polyfill isnt working

**Comment by purtuga** [comment]
@atisawd,
I will not be able to look at it in detail until Monday the earliest.

I'm not sure what you tried, but I just did a quick edit to the last prototype I created in codepen to use the new file name in the 'dist/' folder. Can you try this in IE and FF?

https://codepen.io/anon/pen/eKqEMp?editors=1000

Paul

-- sent from mobile

**Comment by atisawd** [comment]
It's taken care, I did not change the filename in we pack config

**Comment by atisawd** [comment]
Thanks again for your work @purtuga :smile:
